[project]
name = "postcode_parse"
description = "Parses postcodes to present in a particular pattern"
authors = [
  {name = "Matthew Armstrong"},
]
readme = "README.md"
requires-python = ">=3.7"
dependencies = [
"simplekml==1.3.6",
"tqdm==4.64.1"
]
version = "0.0.0"

[project.optional-dependencies]
dev = [
  "ruff"
]

[tool.ruff]
line-length = 120

[tool.ruff.lint]
select = [
    # pycodestyle
    "E",
    # pycodestyle warnings
    "W",
    # pyflakes
    "F",
    # flake8-comprehensions
    "C",
    # pyupgrade
    "UP",
    # flake8-bugbear
    "B",
    # flake8-simplify
    "SIM",
    # isort
    "I",
    # mccabe
    "C90",
    # pep8-naming
    "N",
    # flake8-annotations
    "ANN",
]

[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"
