[project]
name = "postcode_parse"
description = "Parses postcodes to present in a particular pattern"
authors = [
  {name = "Matthew Armstrong"},
]
readme = "README.md"
requires-python = ">=3.7"
dependencies = [
"simplekml==1.3.6",
"tqdm==4.64.1"
]
version = "0.0.0"

[project.optional-dependencies]
dev = [
  "flake8"
]

[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"
